name: PythonTests
  
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with pytest-cov
      run: |
        pip install pytest pytest-cov
        pytest test.py --cov --cov-report=xml --cov-report=html